### ISSUE TITLE
Не работает для муниципальных выборов

### ISSUE THREAD

**Issue by VadBar13** [kbespalov/voting2021#1]
Не расшифровывает муниципальные выборы. Видимо, из-за множественного выбора в бюллетене.

Ошибка: "Failed to parse Choices proto proto: cannot parse invalid wire-format data"

**Comment by kbespalov** [comment]
Можешь пример привести? message и key

**Comment by VadBar13** [comment]
> Можешь пример привести? message и key

Приведу для сравнения МГД и муниципальное (ключ у всех общий 54e3cf70f712b2ff727bde3849772fa811a9d5de796aa7d788d205aa86af04ad)

МГД: `hash: f86d70063a88fbbd124562f9a061f59f41919d3c927196ef7b19faa9e434f9de
message: 0aae010aab010a0508e907100612a1010a406664343533373836643963643035613765633462613135636237653931313838626333313761393461623231336362366166303533613037643230393238656110251a5b0a1901c6ba080b135cd727c859ce7bd353d54d0acc055e62d29c9b121a0a18868c03bffabe72dca3e6ba3cadabaa2a9241120f5c1675fc1a220a200bd69492bc0fe1a8c758840149fe58e61461c72e17e87167c4f9bd0828013f0612220a2085d59d3c86d6562d7adcef11b8b058ea3e95b5760188850827d03904a286689c1a420a408ed6cd610a8f9613f04f5427e1648756a79f55a09b23efccacb7f91934ff4ab623c5296b9adc778b0459742924876935c3f25c0ea387cd86dd3d85ae023a6a0d
block_height: 1057840
position_in_block: 9
location_proof: {"proof":[{"index":8,"height":1,"hash":"b192c523e3f43e2427a83e46ad7cf700ea72584d34596a67298fe5b419cf4e71"},{"index":0,"height":4,"hash":"63dd197c2f9af2a27c6d2ac19e6600312e8abda0c0fae36085b43a7683fb876f"}],"entries":[[9,"f86d70063a88fbbd124562f9a061f59f41919d3c927196ef7b19faa9e434f9de"]],"length":10}
instance_id: 1001
method_id: 6
status: {"type":"success"}
datetime: 2021-09-19 20:19:06
author: 85d59d3c86d6562d7adcef11b8b058ea3e95b5760188850827d03904a286689c
payload: {"voting_id":"fd453786d9cd05a7ec4ba15cb7e91188bc317a94ab213cb6af053a07d20928ea","district_id":37,"encrypted_choice":{"encrypted_message":"01c6ba080b135cd727c859ce7bd353d54d0acc055e62d29c9b","nonce":"868c03bffabe72dca3e6ba3cadabaa2a9241120f5c1675fc","public_key":"0bd69492bc0fe1a8c758840149fe58e61461c72e17e87167c4f9bd0828013f06"}}
signature: 8ed6cd610a8f9613f04f5427e1648756a79f55a09b23efccacb7f91934ff4ab623c5296b9adc778b0459742924876935c3f25c0ea387cd86dd3d85ae023a6a0d
store_tx_hash: f86d70063a88fbbd124562f9a061f59f41919d3c927196ef7b19faa9e434f9de
voting_id: fd453786d9cd05a7ec4ba15cb7e91188bc317a94ab213cb6af053a07d20928ea
district_number: 37
voter_address: 85d59d3c86d6562d7adcef11b8b058ea3e95b5760188850827d03904a286689c
decrypt_tx_hash: bb4b47a8a063ff261c86bcdabcd50b5d517ac72f57e8552f1484682bb66f492e
decrypted_choice: ["142558777"]
ballot_status: Valid`

Щукино: `hash: 9d540d8b6bf1a20223d8265141a02b33ac89c1e4b2a558e4e4e4495fc3272218
message: 0ab8010ab5010a0508e907100612ab010a406166646138313461363861353833323832613039343035613637373661383464663937616364646161646533633030393366306531356261363063353536316610031a650a233856b667c4c222b22f70d5970b9f8f0c5eb0f171a64e6d25f23b48891f7a8f945aa3ef121a0a18b98035dbdac7d53779174076a64f74f491aab4386d9e3dab1a220a20d357df8d2b9a6f3a9a886aa82aa357b811a7557c9e4d0dd998f30e3bf411684f12220a20583797e89e1248cb103a69493df53dae477b6456d531db0bd0259dc0a2fda0381a420a409c7a8809c4bdfc32501cac4b754eb7e7240daf81aa7271e159826b9958d6e79bcf3699399a84f648681cafe4ba7f511b362d48c6515a0b14c41bb15ab8e61706
block_height: 1028713
position_in_block: 1
location_proof: {"proof":[{"index":0,"height":1,"hash":"7d555e983796c9cac6a7b20581675b152ef4faaff6f34bb325d153211ec4bd9b"}],"entries":[[1,"9d540d8b6bf1a20223d8265141a02b33ac89c1e4b2a558e4e4e4495fc3272218"]],"length":2}
instance_id: 1001
method_id: 6
status: {"type":"success"}
datetime: 2021-09-19 20:19:09
author: 583797e89e1248cb103a69493df53dae477b6456d531db0bd0259dc0a2fda038
payload: {"voting_id":"afda814a68a583282a09405a6776a84df97acddaade3c0093f0e15ba60c5561f","district_id":3,"encrypted_choice":{"encrypted_message":"3856b667c4c222b22f70d5970b9f8f0c5eb0f171a64e6d25f23b48891f7a8f945aa3ef","nonce":"b98035dbdac7d53779174076a64f74f491aab4386d9e3dab","public_key":"d357df8d2b9a6f3a9a886aa82aa357b811a7557c9e4d0dd998f30e3bf411684f"}}
signature: 9c7a8809c4bdfc32501cac4b754eb7e7240daf81aa7271e159826b9958d6e79bcf3699399a84f648681cafe4ba7f511b362d48c6515a0b14c41bb15ab8e61706
store_tx_hash: 9d540d8b6bf1a20223d8265141a02b33ac89c1e4b2a558e4e4e4495fc3272218
voting_id: afda814a68a583282a09405a6776a84df97acddaade3c0093f0e15ba60c5561f
district_number: 3
voter_address: 583797e89e1248cb103a69493df53dae477b6456d531db0bd0259dc0a2fda038
decrypt_tx_hash: fcdf6abe7f8bc4eccb4b7702cb45bd426ad3aeedeca12cce19ad9325a58d95c8
decrypted_choice: ["107466233","112447822","242048688"]
ballot_status: Valid`

**Comment by kbespalov** [comment]
<img width="961" alt="Снимок экрана 2021-09-29 в 02 27 41" src="https://user-images.githubusercontent.com/15847176/135178972-033c720f-83c8-42a5-921a-152bd3a62fc6.png">

Странно, у меня работает:

[test.csv](https://github.com/kbespalov/voting2021/files/7247814/test.csv)

В нужном формате передаете?
.

**Comment by VadBar13** [comment]
> <img alt="Снимок экрана 2021-09-29 в 02 27 41" width="961" src="https://user-images.githubusercontent.com/15847176/135178972-033c720f-83c8-42a5-921a-152bd3a62fc6.png">
> 
> Странно, у меня работает:
> 
> [test.csv](https://github.com/kbespalov/voting2021/files/7247814/test.csv)
> 
> В нужном формате передаете? .

Это у Вас МГД. Он работает. Я его привёл для сравнения. Муниципальная транзакция вот: `hash: 9d540d8b6bf1a20223d8265141a02b33ac89c1e4b2a558e4e4e4495fc3272218 message: 0ab8010ab5010a0508e907100612ab010a406166646138313461363861353833323832613039343035613637373661383464663937616364646161646533633030393366306531356261363063353536316610031a650a233856b667c4c222b22f70d5970b9f8f0c5eb0f171a64e6d25f23b48891f7a8f945aa3ef121a0a18b98035dbdac7d53779174076a64f74f491aab4386d9e3dab1a220a20d357df8d2b9a6f3a9a886aa82aa357b811a7557c9e4d0dd998f30e3bf411684f12220a20583797e89e1248cb103a69493df53dae477b6456d531db0bd0259dc0a2fda0381a420a409c7a8809c4bdfc32501cac4b754eb7e7240daf81aa7271e159826b9958d6e79bcf3699399a84f648681cafe4ba7f511b362d48c6515a0b14c41bb15ab8e61706 block_height: 1028713 position_in_block: 1 location_proof: {"proof":[{"index":0,"height":1,"hash":"7d555e983796c9cac6a7b20581675b152ef4faaff6f34bb325d153211ec4bd9b"}],"entries":[[1,"9d540d8b6bf1a20223d8265141a02b33ac89c1e4b2a558e4e4e4495fc3272218"]],"length":2} instance_id: 1001 method_id: 6 status: {"type":"success"} datetime: 2021-09-19 20:19:09 author: 583797e89e1248cb103a69493df53dae477b6456d531db0bd0259dc0a2fda038 payload: {"voting_id":"afda814a68a583282a09405a6776a84df97acddaade3c0093f0e15ba60c5561f","district_id":3,"encrypted_choice":{"encrypted_message":"3856b667c4c222b22f70d5970b9f8f0c5eb0f171a64e6d25f23b48891f7a8f945aa3ef","nonce":"b98035dbdac7d53779174076a64f74f491aab4386d9e3dab","public_key":"d357df8d2b9a6f3a9a886aa82aa357b811a7557c9e4d0dd998f30e3bf411684f"}} signature: 9c7a8809c4bdfc32501cac4b754eb7e7240daf81aa7271e159826b9958d6e79bcf3699399a84f648681cafe4ba7f511b362d48c6515a0b14c41bb15ab8e61706 store_tx_hash: 9d540d8b6bf1a20223d8265141a02b33ac89c1e4b2a558e4e4e4495fc3272218 voting_id: afda814a68a583282a09405a6776a84df97acddaade3c0093f0e15ba60c5561f district_number: 3 voter_address: 583797e89e1248cb103a69493df53dae477b6456d531db0bd0259dc0a2fda038 decrypt_tx_hash: fcdf6abe7f8bc4eccb4b7702cb45bd426ad3aeedeca12cce19ad9325a58d95c8 decrypted_choice: ["107466233","112447822","242048688"] ballot_status: Valid`

**Comment by kbespalov** [comment]
Не сообразил как лучше сделать, но решение здесь:

https://github.com/kbespalov/voting2021/commit/d622996737c0f433cc4f71fc62d9ec315d5edca5

Попробуйте пожалуйста пересобрать.

**Comment by VadBar13** [comment]
> 
> 
> Не сообразил как лучше сделать, но решение здесь:
> 
> [d622996](https://github.com/kbespalov/voting2021/commit/d622996737c0f433cc4f71fc62d9ec315d5edca5)
> 
> Попробуйте пожалуйста пересобрать.

Благодарю. На первый взгляд работает.
